# Generated by Django 2.1.5 on 2021-03-06 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 21, 30, 5, 845518), verbose_name='date published'),
        ),
    ]
