# Generated by Django 2.1.5 on 2021-03-11 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210306_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 19, 47, 39, 414292), verbose_name='date published'),
        ),
    ]
